@extends('admin.auth.dashboardAmin')

@section('title', 'Danh sách hoàn và đổi hàng')

@section('admin_content')
<div class="container-fluid py-4">
    <div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="mb-1">Hoàn và đổi hàng</h2><div class="text-muted">Theo dõi ai hoàn đơn, hoàn bao nhiêu, trả tiền hay đổi sản phẩm.</div></div><a class="btn btn-outline-primary" href="{{ route('admin.orders.index') }}">Danh sách đơn hàng</a></div>
    <div class="row g-3 mb-4">
        <div class="col-md-3"><div class="card card-body"><small>Tổng phiếu</small><strong class="fs-4">{{ $summary->total_count }}</strong></div></div>
        <div class="col-md-3"><div class="card card-body"><small>Giá trị hàng trả</small><strong class="fs-4">{{ number_format((float)$summary->returned_value,0,',','.') }}đ</strong></div></div>
        <div class="col-md-3"><div class="card card-body"><small>Phải hoàn tiền</small><strong class="fs-4 text-danger">{{ number_format((float)$summary->cash_refund,0,',','.') }}đ</strong></div></div>
        <div class="col-md-3"><div class="card card-body"><small>Giá trị đổi hàng</small><strong class="fs-4 text-primary">{{ number_format((float)$summary->exchange_credit,0,',','.') }}đ</strong></div></div>
    </div>
    <form method="GET" class="card card-body mb-3"><div class="row g-2"><div class="col-md-5"><input class="form-control" name="keyword" value="{{ $keyword }}" placeholder="Mã phiếu, mã đơn, tên hoặc SĐT khách"></div><div class="col-md-3"><select class="form-select" name="type"><option value="">Mọi hình thức</option><option value="refund" @selected($type==='refund')>Hoàn tiền</option><option value="exchange" @selected($type==='exchange')>Đổi sản phẩm</option><option value="mixed" @selected($type==='mixed')>Hoàn tiền + đổi hàng</option></select></div><div class="col-md-3"><select class="form-select" name="status"><option value="">Mọi trạng thái</option><option value="completed" @selected($status==='completed')>Đã xử lý</option><option value="pending_exchange" @selected($status==='pending_exchange')>Chờ giao hàng đổi</option></select></div><div class="col-md-1"><button class="btn btn-primary w-100">Lọc</button></div></div></form>
    @forelse($returns as $return)
    <div class="card mb-3"><div class="card-header d-flex justify-content-between flex-wrap gap-2"><div><strong>{{ $return->return_code }}</strong> · Đơn <a href="{{ route('admin.orders.show',$return->order) }}">{{ $return->order->order_code }}</a></div><span class="badge bg-{{ $return->resolution_status==='pending_exchange'?'warning text-dark':'success' }}">{{ $return->resolution_status==='pending_exchange'?'Chờ giao hàng đổi':'Đã xử lý' }}</span></div>
                <div class="card-body"><div class="row g-3"><div class="col-lg-4"><strong>Khách hoàn:</strong> {{ $return->order->customer->full_name }}<br><span class="text-muted">{{ $return->order->customer->phone }}</span><br><strong>Người lập phiếu:</strong> {{ $return->creator?->name ?? 'Hệ thống' }}<br><strong>Thời gian:</strong> {{ $return->returned_at?->format('d/m/Y H:i') }}</div><div class="col-lg-4"><strong>Sản phẩm hoàn:</strong><ul class="mb-1">@foreach($return->items as $item)<li>{{ $item->orderItem?->product_name }} × {{ $item->quantity }}</li>@endforeach</ul><strong>Lý do:</strong> {{ $return->reason }}</div><div class="col-lg-4"><div>Giá trị trả: <strong>{{ number_format((float)$return->refund_amount,0,',','.') }}đ</strong></div><div>Hoàn tiền: <strong class="text-danger">{{ number_format((float)$return->cash_refund_amount,0,',','.') }}đ</strong></div><div>Đổi hàng: <strong class="text-primary">{{ number_format((float)$return->exchange_credit_amount,0,',','.') }}đ</strong></div><div class="mt-2"><span class="badge bg-secondary">{{ ['refund'=>'Hoàn tiền','exchange'=>'Đổi sản phẩm','mixed'=>'Hoàn + đổi'][$return->resolution_type] ?? $return->resolution_type }}</span></div>@if($return->exchange_note)<div class="mt-2"><strong>Yêu cầu đổi:</strong> {{ $return->exchange_note }}</div>@endif @if($return->resolution_status==='pending_exchange')<form method="POST" action="{{ route('admin.orders.returns.complete-exchange',$return) }}" class="mt-3">@csrf @method('PATCH')<input class="form-control form-control-sm mb-2" name="completion_note" placeholder="Sản phẩm đã giao/mã vận đơn"><button class="btn btn-sm btn-success" onclick="return confirm('Xác nhận đã giao sản phẩm đổi cho khách?')">Đã giao sản phẩm đổi</button></form>@endif</div></div></div>
    </div>
    @empty<div class="alert alert-info">Chưa có phiếu hoàn/đổi phù hợp.</div>@endforelse
    {{ $returns->links() }}
</div>
@endsection
